/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f407xx.h"

void delay(void) {
	for(uint32_t i=0; i < 320000; i++);
}

int main(void)
{
	GPIO_Handle_t Led_01;

	Led_01.pGPIOx = GPIOD;
	Led_01.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	Led_01.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led_01.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led_01.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led_01.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&Led_01);

	while(1) {
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		delay();
	}

	return 0;
}
