/*
 * 002_button.c
 *
 *  Created on: Mar 23, 2020
 *      Author: vladi
 */


/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f407xx.h"

#define HIGH			ENABLE
#define BTN_PRESSED		HIGH

void delay(void) {
	for(uint32_t i=0; i < 320000; i++);
}

int main(void)
{
	GPIO_Handle_t Led_01, Button_01;

	Led_01.pGPIOx = GPIOD;
	Led_01.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	Led_01.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led_01.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led_01.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led_01.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&Led_01);

	Button_01.pGPIOx = GPIOA;
	Button_01.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	Button_01.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	Button_01.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Button_01.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&Button_01);

	// IRQ Configuration
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, 15);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);

	while(1);

	//return 0;
}

void EXTI0_IRQHandler(void) {
	GPIO_IRQHandling(0);
	GPIO_ToggleOutputPin(GPIOD, 12);
}

